image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка
    - DZ18.2

build: off  # будем использовать свой скрипт сборки

install:
  - chmod +x gradlew
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-ibank.jar &

build_script:
  - ./gradlew test -Dselenide.headless=true -P:profile=test --info # запускаем тест, флаг --info позволяет выводить больше информации
#  - -Dselenide.headless=true