image: Ubuntu

stack: jdk 11

branches:
  only:
    - main
    - DZ18.2

build: off

install:
  - chmod +x gradlew
  - java -jar ./artifacts/app-ibank.jar -P:profile=test &

build_script:
  - ./gradlew test -Dselenide.headless=true --info